name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Zip build directory
      uses: papeloto/action-zip@v1
      with:
        files: ./build
        recursive: false
        dest: build.zip
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.3.0
      with:
        name: build-artifact
        path: ./build.zip
        retention-days: 1
